import type { Assessment } from "./assessmentsApi"

const SHARED_DESC =
  'Read, write, discuss, and represent whole numbers up to 100,000. Representations should include numerals, words, pictures, number lines, and manipulatives.'

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    id: 1,
    type: 'practice-quiz',
    title: 'Practice Quiz',
    scheduledDate: null,
    lastActivity: '8-26-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 25, total: 25 },
    independentPractice: { completed: 20, total: 25, mastery: 78 },
    continuousPractice: { completed: 18, total: 25, mastery: 50 },
    formativeQuiz: { completed: 25, total: 25, mastery: 28 },
  },
  {
    id: 2,
    type: 'standard',
    title: '3.N.1.1 – Number & Operations',
    scheduledDate: 'Tue Sep 9',
    lastActivity: '9-2-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 23, total: 25 },
    independentPractice: { completed: 20, total: 25, mastery: 78 },
    continuousPractice: { completed: 18, total: 25, mastery: 50 },
    formativeQuiz: { completed: 20, total: 25, mastery: 28 },
    studentsNeedingAttention: 6,
  },
  {
    id: 3,
    type: 'standard',
    title: '3.N.1.2 – Number & Operations',
    hasStrengthIcon: true,
    scheduledDate: 'Thu Sep 11',
    lastActivity: '9-2-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 23, total: 25 },
    independentPractice: { completed: 20, total: 25, mastery: 78 },
    continuousPractice: { completed: 18, total: 25, mastery: 50 },
    formativeQuiz: { completed: 12, total: 25, mastery: 72 },
    studentsNeedingAttention: 2,
  },
  {
    id: 4,
    type: 'standard',
    title: '3.N.1.3 – Number & Operations',
    scheduledDate: 'Tue Sep 16',
    lastActivity: '9-10-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 25, total: 25 },
    independentPractice: { completed: 22, total: 25, mastery: 84 },
    continuousPractice: { completed: 20, total: 25, mastery: 66 },
    formativeQuiz: { completed: 19, total: 25, mastery: 61 },
    studentsNeedingAttention: 4,
  },
  {
    id: 5,
    type: 'standard',
    title: '3.N.1.4 – Number & Operations',
    hasStrengthIcon: true,
    scheduledDate: 'Thu Sep 18',
    lastActivity: '9-12-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 24, total: 25 },
    independentPractice: { completed: 21, total: 25, mastery: 76 },
    continuousPractice: { completed: 17, total: 25, mastery: 52 },
    formativeQuiz: { completed: 18, total: 25, mastery: 55 },
    studentsNeedingAttention: 7,
  },
  {
    id: 6,
    type: 'standard',
    title: '3.N.2.1 – Addition & Subtraction',
    scheduledDate: 'Tue Sep 23',
    lastActivity: '9-18-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 22, total: 25 },
    independentPractice: { completed: 17, total: 25, mastery: 69 },
    continuousPractice: { completed: 15, total: 25, mastery: 48 },
    formativeQuiz: { completed: 17, total: 25, mastery: 45 },
    studentsNeedingAttention: 8,
  },
  {
    id: 7,
    type: 'standard',
    title: '3.N.2.2 – Addition & Subtraction',
    scheduledDate: 'Thu Sep 25',
    lastActivity: '9-19-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 25, total: 25 },
    independentPractice: { completed: 24, total: 25, mastery: 91 },
    continuousPractice: { completed: 22, total: 25, mastery: 80 },
    formativeQuiz: { completed: 23, total: 25, mastery: 86 },
    studentsNeedingAttention: 1,
  },
  {
    id: 8,
    type: 'standard',
    title: '3.N.3.1 – Multiplication',
    hasStrengthIcon: true,
    scheduledDate: 'Tue Sep 30',
    lastActivity: '9-24-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 21, total: 25 },
    independentPractice: { completed: 16, total: 25, mastery: 62 },
    continuousPractice: { completed: 13, total: 25, mastery: 44 },
    formativeQuiz: { completed: 14, total: 25, mastery: 40 },
    studentsNeedingAttention: 9,
  },
  {
    id: 9,
    type: 'standard',
    title: '3.N.3.2 – Multiplication',
    scheduledDate: 'Thu Oct 2',
    lastActivity: '9-26-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 20, total: 25 },
    independentPractice: { completed: 18, total: 25, mastery: 73 },
    continuousPractice: { completed: 16, total: 25, mastery: 56 },
    formativeQuiz: { completed: 16, total: 25, mastery: 52 },
    studentsNeedingAttention: 5,
  },
  {
    id: 10,
    type: 'standard',
    title: '3.N.3.3 – Multiplication',
    hasStrengthIcon: true,
    scheduledDate: 'Tue Oct 7',
    lastActivity: '10-1-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 20, total: 25 },
    independentPractice: { completed: 17, total: 25, mastery: 68 },
    continuousPractice: { completed: 14, total: 25, mastery: 54 },
    formativeQuiz: { completed: 15, total: 25, mastery: 50 },
  },
  {
    id: 11,
    type: 'standard',
    title: '3.N.4.1 – Division',
    scheduledDate: 'Thu Oct 9',
    lastActivity: '10-3-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 19, total: 25 },
    independentPractice: { completed: 14, total: 25, mastery: 58 },
    continuousPractice: { completed: 11, total: 25, mastery: 42 },
    formativeQuiz: { completed: 13, total: 25, mastery: 38 },
    studentsNeedingAttention: 10,
  },
  {
    id: 12,
    type: 'standard',
    title: '3.N.4.2 – Division',
    scheduledDate: 'Tue Oct 14',
    lastActivity: '10-7-26',
    description: SHARED_DESC,
    lessonGuidedPractice: { completed: 18, total: 25 },
    independentPractice: { completed: 15, total: 25, mastery: 63 },
    continuousPractice: { completed: 12, total: 25, mastery: 47 },
    formativeQuiz: { completed: 11, total: 25, mastery: 35 },
    studentsNeedingAttention: 11,
  },
]
